spring:
  datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/security_db
      username: root
      password:
  jpa:
    hibernate:
      ddl-auto: create
  logging:
    level
  thymeleaf:
    encoding: utf-8